### ISSUE TITLE
web.php is outdated

### ISSUE THREAD

**Issue by ghost** [LaravelDaily/Laravel-FullCalendar-Sources#1]
Hi,

I just tested the app and looks like the routes are old. The Controller and Resource files are in different locations. Please modify it. I have modified it and working well for me. Let me know if i can be nay help for you.

Regards
Ansif

**Comment by PovilasKorop** [comment]
@ansifpi sorry I didn't understand what you mean by Controller and Resource in different locations. They should be in different locations. How exactly did you modify them?

**Comment by ghost** [comment]
Hi,

Thanks for the mail. Yeah that's correct. The folders are not properly
routed in web.php file. For example, the root is redirected to a login page
which is not there. Also the resources/views/admin folder should include
the same home.blade.php that is located in the resources/views folder.
Similarly the Controller files are stored in folders like admin,auth etc.
But web.php is routing to app/Http only.

I think a proper change in web.php will fix all these issues.

Regards
Ansif

Software Consultant
___________________________________
Mobile/WhatsApp: +919544139564

Skype: ansif.ibrahim

**Comment by PovilasKorop** [comment]
@ansifpi I think you're wrong. 

- Login page is there, how can it not be there? It was all working last time I checked.
- Subfolders of `resources/views` is a personal preference, you can create subfolder `/admin` or not
- `web.php` is routing with `Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin',` so admin prefix is there. To separate from future non-admin pages.

In the end, I'm not sure what to fix cause the app itself is working, no one else complained about anything like this.

**Comment by ghost** [comment]
Ok. Can you test the latest code. May be the web.php is still using old
code. May be i am wrong. Please if you have time.

Regards
Ansif

Software Consultant
___________________________________
Mobile/WhatsApp: +919544139564

Skype: ansif.ibrahim

**Comment by PovilasKorop** [comment]
@ansifpi I don't have much time, to be honest, could you send the exact screenshot of what was not working for you? Exact error. Cause now I don't see any reason for fixing anything, except for your personal preference where files should be located.

**Comment by ghost** [comment]
Yes i will sent it soon.

Regards
Ansif

Software Consultant
___________________________________
Mobile/WhatsApp: +919544139564

Skype: ansif.ibrahim

**Comment by ghost** [comment]
Sorry was busy with my Laravel works. I have added the the updated code here. You can see the changes in views/resources folder and also in app/Http/Controllers folder. Also the web.php file.

https://drive.google.com/open?id=1rCZrZSH_udcyBkjmgxdfjBIGel1HhEGr

Regards
Ansif

**Comment by PovilasKorop** [comment]
@ansifpi wait, before me looking at the code - you still didn't answer what was the ISSUE? What was the ERROR MESSAGE before these changes, why were they needed?

**Comment by ghost** [comment]
Hi,

When i open the app in my browser it goes to unknown login page which is
not in the code. Please see below the code in web.php file.

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status',
session('status'));
    }

    return redirect()->route('admin.home');
});

"Route::redirect('/', '/login');" - This login is not found anywhere in the
code and this goes to server error.
  route('admin.home') - no home.blade.php file in admin folder.

The above are some of the issues i found. there are other issues which have
changed in the code i shared it with you. Please compare it with your repo.

Ansif
Software Consultant
__________________________________
Mobile/WhatsApp: +919544139564
Skype: ansif.ibrahim
Blog: Technoposts.com

**Comment by PovilasKorop** [comment]
@ansifpi 

1. "login is not in the code" because it's inside of default Laravel auth routes in __routes/web.php__:

```
Auth::routes(['register' => false]);
```

2. `route('admin.home')` is not for Blade file, it's referencing this line `Route::get('/', 'HomeController@index')->name('home');` which has name of "home" within a group with prefix "admin" - `Route::group(['prefix' => 'admin'`

So I still don't see what needs to be fixed and why.

**Comment by ghost** [comment]
Yeah.. but it fails in my system. Can you build the app and run in a fresh
system. I think its already registered in your system and goes inside the
admin route. For me, it goes to /login which is not in my code. I think
login should route to register page but its not happened in my system.

Regards
Ansif
Software Consultant
__________________________________
Mobile/WhatsApp: +919544139564
Skype: ansif.ibrahim

**Comment by PovilasKorop** [comment]
I did install the system and it did redirect me to /login, as it SHOULD do, that's default Laravel login logic, we didn't invent that /login, it's Auth::routes()

So, again, nothing to fix here, not sure why it didn't work for you.

**Comment by ghost** [comment]
Ok i got it. Actually the Laravel installation is not properly configured
in my system. Because of that it didnt go to the login page. Its my fault.
Sorry please close the issue..

Regards
Ansif
Software Consultant
__________________________________
Mobile/WhatsApp: +919544139564
Skype: ansif.ibrahim
